spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false

logging:
  level:
    com.sercan.catalog: INFO
